language: node_js
node_js: 
  - "stable"
install:
  - npm install
script:
  - npm run coverage
  - npm run coveralls
addons:
  artifacts:
    target_paths:
    - /
    debug: true

cache:
  directories:
    - "node_modules"
    - "src"
notifications:
  - email: false
